import React from 'react'
import type { Metadata } from "next";
import "./globals.css";
import Navbar from '@/components/Navbar';


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


const RootLayout = async ({ children, }: Readonly<{ children: React.ReactNode; }>) => {
  return (
    <html lang="en">
      <body className=' font-[sans-serif]'>
        <Navbar />
        {children}
      </body>
    </html>
  )
}

export default RootLayout

